Add workflow deploy app

diff --git a/.github/workflows/app.yaml b/.github/workflows/app.yaml
--- a/.github/workflows/app.yaml
+++ b/.github/workflows/app.yaml
@@ -1,15 +1,25 @@
+name: Deploy App FastApi
+
 on:
-    push:
-      branches: [ main ]
+  workflow_run:
+    workflows:
+      - Python
+    types:
+      - completed
   
-  name: Deploy New Version App FastApi
-  
-  jobs:
-    build:
-      name: Build
-      runs-on: ubuntu-latest
-  
-      steps:
+jobs:
+  build:
+    name: Build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Workflow Python status
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
+            echo "Workflow Python was successful."
+          else
+            echo "Workflow Python failed."
+            exit 1
+          fi
       - name: Checkout
         uses: actions/checkout@v3
   
@@ -41,30 +51,30 @@ on:
           echo "Pushing Docker image to ECR..."
           docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
           echo "Docker image pushed successfully."
-    
-    deploy_prod:
-      name: deploy_prod
-      needs: [deploy_dev]
-      environment: 
-        name: production
-        url: http://final-project.devops-fairy.cloudns.biz/
-      runs-on: ubuntu-latest
   
-      steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
-          
-      - name: Update kube config
-        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}
-  
-      - name: Clone charts HELM
-        run: |
-          git clone https://github.com/FastAndTraefik/fastapi-docker-traefik.git
-  
-      - name: Install Charts db and Fastapi - prod
-        run: |
-          helm upgrade --install fastapi-db ./yaml-files/fastapi-app-chart --values=./yaml-files/fastapi-app-chart/values.yaml --namespace prod
+  deploy_prod:
+    name: deploy_prod
+    needs: [deploy_dev]
+    environment: 
+      name: production
+      url: http://final-project.devops-fairy.cloudns.biz/
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
+        
+    - name: Update kube config
+      run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}
+
+    - name: Clone charts HELM
+      run: |
+        git clone https://github.com/FastAndTraefik/fastapi-docker-traefik.git
+
+    - name: Install Charts db and Fastapi - prod
+      run: |
+        helm upgrade --install fastapi-db ./yaml-files/fastapi-app-chart --values=./yaml-files/fastapi-app-chart/values.yaml --namespace prod
